name: CI

on:
  push:
  pull_request:

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 'true'

jobs:
  test:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
        dotnet-quality: 'ga'
        cache: true
    - run: dotnet restore --locked-mode
    - run: dotnet test --configuration Release

  build:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
        dotnet-quality: 'ga'
        cache: true
    - run: dotnet restore --locked-mode
    - run: dotnet build --configuration Release
